import { PrismaClient } from '../../src/generated/prisma/client.js';

function formatDateOffset(daysFromNow: number) {
  const date = new Date();
  date.setHours(0, 0, 0, 0);
  date.setDate(date.getDate() + daysFromNow);
  return date.toISOString().slice(0, 10);
}

export async function seedEvents(prisma: PrismaClient, channelIds: Record<string, { id: string }>) {
  const music    = channelIds['feeti-music']!.id;
  const sport    = channelIds['feeti-sport']!.id;
  const cinema   = channelIds['feeti-cinema']!.id;
  const business = channelIds['feeti-business']!.id;
  const art      = channelIds['feeti-art']!.id;

  const events = [
    // ── Événements originaux ──────────────────────────────────────────────────
    {
      title: 'AFRO JEMBE JAIYE',
      description: 'Grand concert afro en direct depuis Brazzaville avec captation multicamera.',
      date: formatDateOffset(1),
      time: '20:00',
      duration: '3h00',
      image: 'https://images.unsplash.com/photo-1501386761578-eac5c94b800a?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Concert',
      tags: JSON.stringify(['afro', 'live', 'musique']),
      isLive: true,
      isReplay: false,
      isFeatured: true,
      isFree: false,
      price: 12000,
      currency: 'FCFA',
      viewerCount: 1240,
      streamUrl: 'https://example.com/streams/afro-jembe-jaiye',
      location: 'Palais des Sports, Brazzaville',
    },
    {
      title: 'Champions League Live',
      description: 'Suivez le match en direct avec commentaires en francais.',
      date: formatDateOffset(3),
      time: '21:00',
      duration: '2h00',
      image: 'https://images.unsplash.com/photo-1547347298-4074fc3086f0?auto=format&fit=crop&w=1200&q=80',
      channelId: sport,
      channelName: 'Feeti Sport',
      category: 'Sport',
      tags: JSON.stringify(['football', 'ligue des champions', 'live']),
      isLive: true,
      isReplay: false,
      isFeatured: true,
      isFree: true,
      price: null,
      currency: 'FCFA',
      viewerCount: 5800,
      streamUrl: 'https://example.com/streams/champions-league-live',
      location: 'En ligne',
    },
    {
      title: 'Festival Cinema Africain',
      description: 'Projection des meilleurs films africains suivie d un echange avec les realisateurs.',
      date: formatDateOffset(-10),
      time: '18:00',
      duration: '4h00',
      image: 'https://images.unsplash.com/photo-1517604931442-7e0c8ed2963c?auto=format&fit=crop&w=1200&q=80',
      channelId: cinema,
      channelName: 'Feeti Cinema',
      category: 'Cinema',
      tags: JSON.stringify(['cinema', 'africa', 'culture']),
      isLive: false,
      isReplay: true,
      isFeatured: false,
      isFree: false,
      price: 5000,
      currency: 'FCFA',
      viewerCount: 340,
      streamUrl: 'https://example.com/replays/festival-cinema-africain',
      location: 'Centre Culturel Français, Kinshasa',
    },
    {
      title: 'Conference Tech Africa',
      description: 'Les innovations technologiques en Afrique avec experts et fondateurs.',
      date: formatDateOffset(8),
      time: '09:00',
      duration: '8h00',
      image: 'https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80',
      channelId: business,
      channelName: 'Feeti Business',
      category: 'Conference',
      tags: JSON.stringify(['tech', 'innovation', 'business']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: false,
      price: 15000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Kempinski Hotel, Kinshasa',
    },
    {
      title: 'Art Show Kinshasa',
      description: 'Exposition virtuelle des artistes plasticiens de Kinshasa.',
      date: formatDateOffset(-4),
      time: '15:00',
      duration: '2h00',
      image: 'https://images.unsplash.com/photo-1460661419201-fd4cecdf8a8b?auto=format&fit=crop&w=1200&q=80',
      channelId: art,
      channelName: 'Feeti Art',
      category: 'Art',
      tags: JSON.stringify(['art', 'exposition', 'culture']),
      isLive: false,
      isReplay: true,
      isFeatured: false,
      isFree: true,
      price: null,
      currency: 'FCFA',
      viewerCount: 220,
      streamUrl: 'https://example.com/replays/art-show-kinshasa',
      location: 'Galerie Boboto, Kinshasa',
    },
    {
      title: 'Nuit Rumba Premium',
      description: 'Une nuit premium de rumba congolaise avec acces backstage et captation HD.',
      date: formatDateOffset(14),
      time: '22:00',
      duration: '2h30',
      image: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Concert',
      tags: JSON.stringify(['rumba', 'premium', 'concert']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: false,
      price: 9000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Cercle de Kinshasa, Kinshasa',
    },
    {
      title: 'Talk Show Sport Afrique',
      description: 'Debrief de l actualite sportive africaine avec consultants et invites speciaux.',
      date: formatDateOffset(18),
      time: '19:30',
      duration: '1h30',
      image: 'https://images.unsplash.com/photo-1517649763962-0c623066013b?auto=format&fit=crop&w=1200&q=80',
      channelId: sport,
      channelName: 'Feeti Sport',
      category: 'Sport',
      tags: JSON.stringify(['talk-show', 'sport', 'analyse']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: true,
      price: null,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Studio Feeti Sport, Brazzaville',
    },
    {
      title: 'Masterclass Entrepreneuriat',
      description: 'Masterclass pour lancer et structurer son activite dans les industries creatives.',
      date: formatDateOffset(32),
      time: '11:00',
      duration: '2h00',
      image: 'https://images.unsplash.com/photo-1552664730-d307ca884978?auto=format&fit=crop&w=1200&q=80',
      channelId: business,
      channelName: 'Feeti Business',
      category: 'Business',
      tags: JSON.stringify(['masterclass', 'entrepreneuriat', 'business']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: false,
      price: 7000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'En ligne',
    },
    {
      title: 'Projection Classic Congo',
      description: 'Projection premium d un classique du cinema congolais suivie d un debat.',
      date: formatDateOffset(40),
      time: '20:30',
      duration: '2h10',
      image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=1200&q=80',
      channelId: cinema,
      channelName: 'Feeti Cinema',
      category: 'Cinema',
      tags: JSON.stringify(['cinema', 'classique', 'projection']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: false,
      price: 4000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Ciné Afrique, Brazzaville',
    },

    // ── Événements issus des mocks frontend ───────────────────────────────────
    // (EventDetail + Agenda — à partir d'ici branchés sur la DB)
    {
      title: 'Yaye Padura',
      description: 'Découvrez Yaye Padura dans une soirée exceptionnelle de rumba congolaise. Un événement musical incontournable qui célèbre la richesse de notre patrimoine musical avec les plus grands artistes de la scène locale. Ambiance garantie et show spectaculaire au programme !',
      date: formatDateOffset(0),
      time: '19:00',
      duration: '2h30',
      image: 'https://images.unsplash.com/photo-1514525253161-7a46d19cd819?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Concert',
      tags: JSON.stringify(['rumba', 'concert', 'live']),
      isLive: true,
      isReplay: false,
      isFeatured: true,
      isFree: false,
      price: 3000,
      currency: 'FCFA',
      viewerCount: 420,
      streamUrl: 'https://example.com/streams/yaye-padura',
      location: 'Salle Savorgnon - IFC, Brazzaville',
    },
    {
      title: 'Festival Mbote - Edition 2025',
      description: 'Le plus grand festival de musique d\'Afrique Centrale revient pour une édition mémorable ! Découvrez les meilleurs artistes de la scène africaine dans une ambiance festive et conviviale. Un événement gratuit et ouvert à tous, célébrant la diversité culturelle et musicale.',
      date: formatDateOffset(0),
      time: '14:00',
      duration: '6h00',
      image: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Festival',
      tags: JSON.stringify(['festival', 'musique', 'culture', 'gratuit']),
      isLive: true,
      isReplay: false,
      isFeatured: true,
      isFree: true,
      price: null,
      currency: 'FCFA',
      viewerCount: 3200,
      streamUrl: 'https://example.com/streams/festival-mbote-2025',
      location: 'Stade des Martyrs, Kinshasa',
    },
    {
      title: 'Concert Live Jazz',
      description: 'Soirée jazz intimiste dans le cadre élégant de Chez Ntemba. Les meilleurs musiciens de jazz de la région se réunissent pour une performance acoustique exceptionnelle. Un moment de pure élégance musicale à ne pas manquer.',
      date: formatDateOffset(0),
      time: '20:00',
      duration: '3h00',
      image: 'https://images.unsplash.com/photo-1415201364774-f6f0bb35f28f?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Concert',
      tags: JSON.stringify(['jazz', 'concert', 'live', 'acoustique']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: false,
      price: 8000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Chez Ntemba, Kinshasa',
    },
    {
      title: 'Spectacle Comédie',
      description: 'Une soirée d\'humour et de rires avec les meilleurs comédiens de la ville ! Stand-up, sketchs et improvisation au programme. Venez vous détendre et profiter d\'un moment de pure comédie dans une ambiance chaleureuse.',
      date: formatDateOffset(1),
      time: '21:00',
      duration: '2h00',
      image: 'https://images.unsplash.com/photo-1507924538820-ede94a04019d?auto=format&fit=crop&w=1200&q=80',
      channelId: art,
      channelName: 'Feeti Art',
      category: 'Comedy',
      tags: JSON.stringify(['comédie', 'humour', 'stand-up']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: false,
      price: 12000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Pullman Hotel, Kinshasa',
    },
    {
      title: 'Soirée Danse Afro',
      description: 'Participez à une soirée danse afro exceptionnelle ! Ateliers de danse, performances et DJ sets afro pour une ambiance électrique. Événement gratuit ouvert à tous les passionnés de danse et de culture africaine.',
      date: formatDateOffset(1),
      time: '18:00',
      duration: '4h00',
      image: 'https://images.unsplash.com/photo-1504609813442-a8924e83f76e?auto=format&fit=crop&w=1200&q=80',
      channelId: art,
      channelName: 'Feeti Art',
      category: 'Danse',
      tags: JSON.stringify(['danse', 'afro', 'workshop', 'gratuit']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: true,
      price: null,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Fleuve Congo Hotel, Kinshasa',
    },
    {
      title: 'Concert Afrobeat Paris',
      description: 'Une nuit d\'afrobeat enflammée au cœur de Paris avec les artistes montants de la scène africaine internationale.',
      date: formatDateOffset(2),
      time: '22:00',
      duration: '3h00',
      image: 'https://images.unsplash.com/photo-1470229722913-7c0e2dbbafd3?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Concert',
      tags: JSON.stringify(['afrobeat', 'concert', 'paris', 'diaspora']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: false,
      price: 7500,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Paris Arena, Paris',
    },
    {
      title: 'Festival Amapiano Live',
      description: 'Le festival amapiano débarque à Lyon ! Vibrez au rythme des meilleures productions amapiano avec des artistes venus d\'Afrique du Sud et d\'Europe.',
      date: formatDateOffset(2),
      time: '16:00',
      duration: '5h00',
      image: 'https://images.unsplash.com/photo-1540039155733-5bb30b53aa14?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Festival',
      tags: JSON.stringify(['amapiano', 'festival', 'diaspora', 'gratuit']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: true,
      price: null,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Lyon Zenith, Lyon',
    },
    {
      title: 'Soirée Rumba Congolaise',
      description: 'Bruxelles vibre au son de la rumba congolaise ! Une soirée authentique pour la diaspora congolaise et tous les amoureux de la rumba.',
      date: formatDateOffset(3),
      time: '19:30',
      duration: '3h30',
      image: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Concert',
      tags: JSON.stringify(['rumba', 'congolaise', 'bruxelles', 'diaspora']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: false,
      price: 12000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Bruxelles Expo, Bruxelles',
    },
    {
      title: 'Nuit du Ndombolo',
      description: 'La danse la plus célèbre d\'Afrique Centrale s\'invite à Genève pour une nuit inoubliable. Venez danser et célébrer notre patrimoine culturel.',
      date: formatDateOffset(5),
      time: '21:00',
      duration: '4h00',
      image: 'https://images.unsplash.com/photo-1508700115892-45ecd05ae2ad?auto=format&fit=crop&w=1200&q=80',
      channelId: art,
      channelName: 'Feeti Art',
      category: 'Danse',
      tags: JSON.stringify(['ndombolo', 'danse', 'genève', 'diaspora']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: false,
      price: 9000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Genève Arena, Genève',
    },
    {
      title: 'Concert Gospel Live',
      description: 'Une soirée gospel émouvante avec les meilleurs chœurs et solistes de la communauté africaine de Lausanne. Entrée libre, venez en famille !',
      date: formatDateOffset(5),
      time: '17:00',
      duration: '2h30',
      image: 'https://images.unsplash.com/photo-1526142684086-7ebd69df27a5?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Concert',
      tags: JSON.stringify(['gospel', 'concert', 'lausanne', 'gratuit']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: true,
      price: null,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Lausanne Centre, Lausanne',
    },
    {
      title: 'Concert Dadju Brazzaville',
      description: 'L\'artiste Dadju revient à Brazzaville pour un concert exceptionnel dans la mythique Salle Savorgnon. Un show complet avec ses plus grands tubes.',
      date: formatDateOffset(7),
      time: '20:00',
      duration: '3h00',
      image: 'https://images.unsplash.com/photo-1498038432885-c6f3f1b912ee?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Concert',
      tags: JSON.stringify(['dadju', 'concert', 'brazzaville', 'rnb']),
      isLive: false,
      isReplay: false,
      isFeatured: true,
      isFree: false,
      price: 15000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Salle Savorgnon - IFC, Brazzaville',
    },
    {
      title: 'Festival Afro Jembe Jaiye',
      description: 'Grand festival de musique africaine au Palais des Sports. Des artistes venus de toute l\'Afrique pour une journée de célébration culturelle.',
      date: formatDateOffset(7),
      time: '15:00',
      duration: '6h00',
      image: 'https://images.unsplash.com/photo-1533174072545-7a4b6ad7a6c3?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Festival',
      tags: JSON.stringify(['festival', 'afro', 'jembe', 'culture']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: false,
      price: 5000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Palais des Sports, Kinshasa',
    },
    {
      title: 'Fally Ipupa Live Show',
      description: 'Le roi de la rumba moderne revient sur scène ! Fally Ipupa en concert exceptionnel au Stade des Martyrs. Un show grandiose avec chorégraphies, orchestre live et feux d\'artifice.',
      date: formatDateOffset(10),
      time: '19:00',
      duration: '4h00',
      image: 'https://images.unsplash.com/photo-1563841930606-67e2bce48b78?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Concert',
      tags: JSON.stringify(['fally-ipupa', 'concert', 'rumba', 'kinshasa']),
      isLive: false,
      isReplay: false,
      isFeatured: true,
      isFree: false,
      price: 20000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Stade des Martyrs, Kinshasa',
    },
    {
      title: 'Soirée Jazz Premium',
      description: 'Une soirée jazz d\'exception dans l\'élégant cadre du Centre Culturel Français. Cocktail dînatoire, performance live et improvisation pour une expérience premium.',
      date: formatDateOffset(14),
      time: '21:00',
      duration: '3h00',
      image: 'https://images.unsplash.com/photo-1504704911898-68304a7d2807?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Concert',
      tags: JSON.stringify(['jazz', 'premium', 'concert', 'culture']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: false,
      price: 10000,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Centre Culturel Français, Kinshasa',
    },
    {
      title: 'Festival Urbain Kinshasa',
      description: 'Le plus grand festival urbain de Kinshasa ! Hip-hop, afrobeat, dancehall et street art se réunissent pour 8 heures de célébration culturelle urbaine. Entrée libre !',
      date: formatDateOffset(20),
      time: '16:00',
      duration: '8h00',
      image: 'https://images.unsplash.com/photo-1555680202-c86f0e12f086?auto=format&fit=crop&w=1200&q=80',
      channelId: music,
      channelName: 'Feeti Music',
      category: 'Festival',
      tags: JSON.stringify(['festival', 'urbain', 'kinshasa', 'gratuit', 'hip-hop']),
      isLive: false,
      isReplay: false,
      isFeatured: false,
      isFree: true,
      price: null,
      currency: 'FCFA',
      viewerCount: 0,
      streamUrl: null,
      location: 'Parc de la Vallée, Kinshasa',
    },
  ];

  for (const event of events) {
    const existing = await prisma.streamingEvent.findFirst({ where: { title: event.title } });
    await prisma.streamingEvent.upsert({
      where: { id: existing?.id ?? 'none' },
      update: {
        description: event.description,
        date: event.date,
        time: event.time,
        duration: event.duration,
        image: event.image,
        channelId: event.channelId,
        channelName: event.channelName,
        category: event.category,
        tags: event.tags,
        isLive: event.isLive,
        isReplay: event.isReplay,
        isFeatured: event.isFeatured,
        isFree: event.isFree,
        price: event.price,
        currency: event.currency,
        viewerCount: event.viewerCount,
        streamUrl: event.streamUrl,
        location: event.location,
      },
      create: event,
    });
  }

  console.log('Events seeded:', events.length);
}
